FROM ubuntu:24.04

# make it headless
ENV DEBIAN_FRONTEND=noninteractive 

# install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    gdb \
    cmake \
    git 

# mount the project directory
WORKDIR /app

CMD ["/bin/bash"]