# add_executable(
#     Test_2DStaticObstacle

#     StaticGrid.cpp
# )
# target_link_libraries(
#     Test_2DStaticObstacle

#     TwoD
#     BackendVisualization
# )

# add_executable(
#     Test_2DHybridGrid

#     HybridGrid.cpp
# )
# target_link_libraries(
#     Test_2DHybridGrid

#     TwoD
#     BackendVisualization
# )