
Grid:
  cellSize:
  # the folling are test rooms that could be loaded for planners to use and be tesed with, listed with preloaded obstacles in the space
  TestSpaces:
    Room1:
      xMin:
      xMax:
      yMin:
      yMax:
      zMin:
      zMax:
      obstacle1:
      obstacle2:
      obstacle3:
      obstacle4:
    Room2:
      xMin:
      xMax:
      yMin:
      yMax:
      zMin:
      zMax:
      obstacle1:
      obstacle2:
      obstacle3:
      obstacle4:
    Room3:
      xMin:
      xMax:
      yMin:
      yMax:
      zMin:
      zMax:
      obstacle1:
      obstacle2:
      obstacle3:
      obstacle4:
    Room4:
      xMin:
      xMax:
      yMin:
      yMax:
      zMin:
      zMax:
      obstacle1:
      obstacle2:
      obstacle3:
      obstacle4:
